### PR TITLE
Adjust Rails stack

### PR DESCRIPTION
**Pull request by thebadmonkeydev**
Problem
-------
The Rails stack in the README uses ActiveRecord and other internal pieces of Rails to describe the stack, which to me is missleading, especially compared to the other stacks in the REAME

Solution
--------
I've removed some of the internal Rails pieces and brought the stack more inline with what I believe to be similar to the other stacks.  Let me know if this isn't correct.

### CODE REVIEW

**Comment by dzello** [comment]
Thanks for the PR @thebadmonkeydev - we're taking the stacks in a bit more of a use-case / starter kit focused direction, to avoid getting into traps about what *should* belong where. Have a look at the README and see if that makes sense. Do you have a Rails starter that you like or is there a particular feature or type of Rails app that you could suggest tools around?

**Comment by thebadmonkeydev** [comment]
I mean if we're talking about more like a "starter-pack" approach, I'm a big fan of the stack that comes out of this post https://blog.heroku.com/a-rock-solid-modern-web-stack 

It's basically the stack I turn to when setting up a new side-project...I have a rails template in progress if that's more the thing you're looking for.  I'll review the updated README and see if things are a bit clearer.

Thanks for the feedback @dzello!

**Comment by dzello** [comment]
@thebadmonkeydev Yes! That would be perfect to have!

**Comment by thebadmonkeydev** [comment]
@dzello just pushed an update against the newest README adding my interpretation of the stack mentioned above.  Let me know what you think and if there are any changes necessary.

**Comment by dzello** [comment]
Looks good 👍 Nice to have some Rails on the page. Thanks again!

**Pull request merged**
